# Site wide configuration

title:            
locale:           en_CA
url:              


# Jekyll configuration

permalink:   /:categories/:title/
markdown:    kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: compressed
gems:
  - jekyll-sitemap

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false


# Site owner
owner:
  name: Cory Taylor
  avatar: Cory.jpg
  bio: #"Describe your self."
  email: cory.c.taylor@gmail.com
  disqus-shortname: coryt
  twitter: cctaylor
  facebook: #coryctaylor
  google:
    plus: corytaylor1
    analytics: UA-4576662-1
    verify: n9-Bq-kBr49wJ1mJIegpALDlzym55Qw8oGA9SIXSB-4
    ad-client: 
    ad-slot: 
  bing-verify: 250A841DC8741B0D2D22D0FD919FAE60
  github: coryt
  stackoverflow: 136763/coryt
  linkedin: coryctaylor
  instagram: cctaylor
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
